### ISSUE TITLE
statsd sets

### ISSUE THREAD

**Issue by mrichard** [fasterize/node-statsd-profiler#3]
First nice profiler module. Are you all using this in production?

Curious any plans to add statsd sets? I can submit a PR if you like.

**Comment by dax** [comment]
Yes, we are using it in production.
statsd sets are already implemented via the `count` method.

**Comment by mrichard** [comment]
Ah I see that now. Thanks. Is there a constraint to only send numbers when using set?

**Comment by dax** [comment]
According to the statsd documentation, sets take a number (a count): "StatsD supports counting unique occurences of events between flushes".
